In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('full.csv')

In [3]:
len(df)

770045

In [6]:
df['date'].iloc[-1]

'2024-07-31 15:30:00-04:00'

In [61]:
qqq = df.loc[df['symbol'] == 'XOM']

In [62]:
qqq['date']
qqq['dtt'] = qqq['date'].apply(lambda x: x.split(" ")[0])

/var/folders/tq/_9q_lv1s2bndbr3tzzn08x4r0000gn/T/ipykernel_92908/3443178525.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qqq['dtt'] = qqq['date'].apply(lambda x: x.split(" ")[0])

In [63]:
x = qqq.loc[qqq['dtt'] == "2023-09-08"]

In [64]:
x

,date,v,vw,o,c,h,l,t,n,hour,...,vti_5D_trend,vti_vol_8,vti_vol_28,vti_vol_8_28,symbol_vti_8_diff,symbol_vti_1D_diff,symbol_vti_5D_diff,symbol_vti_vol_8_diff,symbol_vti_vol_28_diff,dtt
698230,2023-09-08 09:00:00-04:00,27033.0,114.5081,114.5500,114.4000,114.5500,114.3000,1.694178e+09,290.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08
698231,2023-09-08 09:30:00-04:00,1510338.0,114.8077,114.5300,115.1700,115.1700,114.3200,1.694180e+09,17217.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08
698232,2023-09-08 10:00:00-04:00,988993.0,115.3996,115.1600,115.5300,115.6600,115.0800,1.694182e+09,12384.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08
698233,2023-09-08 10:30:00-04:00,1120577.0,115.7842,115.5300,115.9000,116.0290,115.4750,1.694183e+09,12566.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08
698234,2023-09-08 11:00:00-04:00,644769.0,115.8561,115.9000,115.8388,115.9950,115.6000,1.694185e+09,8633.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08
698235,2023-09-08 11:30:00-04:00,750386.0,115.6266,115.8300,115.5527,115.8692,115.4500,1.694187e+09,8240.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08
698236,2023-09-08 12:00:00-04:00,540661.0,115.7732,115.5600,115.8300,115.9550,115.4300,1.694189e+09,7124.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08
698237,2023-09-08 12:30:00-04:00,489449.0,115.7769,115.8200,115.8600,115.8900,115.6300,1.694191e+09,5827.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08
698238,2023-09-08 13:00:00-04:00,420861.0,115.7504,115.8550,115.7953,115.8550,115.6700,1.694192e+09,6334.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08
698239,2023-09-08 13:30:00-04:00,417025.0,115.8511,115.7900,115.8865,115.9100,115.7700,1.694194e+09,6286.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08
698240,2023-09-08 14:00:00-04:00,838909.0,115.8435,115.8900,115.8000,116.0500,115.6600,1.694196e+09,10157.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08
698241,2023-09-08 14:30:00-04:00,717786.0,115.7121,115.8000,115.6050,115.8250,115.5700,1.694198e+09,8516.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08
698242,2023-09-08 15:00:00-04:00,698370.0,115.6376,115.6075,115.6050,115.7500,115.5678,1.694200e+09,9229.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08
698243,2023-09-08 15:30:00-04:00,2836509.0,115.5792,115.6100,115.6200,115.7250,115.4150,1.694201e+09,23808.0,15.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-08